version: '3'
services:
  postgresql:
    image: postgres:alpine
    volumes:
      - ./DB/postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: block1
      POSTGRES_PASSWORD: block1
      POSTGRES_DB: block1
    ports:
      - "5432:5432"
  
  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - ./images/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: block1
      MONGO_INITDB_ROOT_USERNAME: block1
      MONGO_INITDB_ROOT_PASSWORD: block1
    ports:
      - "27017:27017"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
      - mailcatcher
      - rabbitmq
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./app:/var/www
      - ./logs/nginx:/var/log/nginx

  php:
    build: ./images/php
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    depends_on:
      - mongo
      - redis
    volumes:
      - ./app:/var/www

  yandex_tank:
    image: direvius/yandex-tank:latest
    volumes:
      - ./yandex.tank:/var/loadtest

  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.8.2
    ports:
      - "1080:1080"
      - "1025:1025"
  
  rabbitmq:
    build: ./images/rabbitmq
    ports:
      - "15672:15672"
        
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  mongo_data:
