<?php

namespace PersistentCollections;

use Doctrine\Common\Collections\Collection as BaseCollection;
use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\MongoDBException;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Utility\CollectionHelper;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE\'S PERSISTENT COLLECTION GENERATOR
 */
class DoctrineCommonCollectionsArrayCollectionPersistent extends \Doctrine\Common\Collections\ArrayCollection implements \Doctrine\ODM\MongoDB\PersistentCollection\PersistentCollectionInterface
{
    use \Doctrine\ODM\MongoDB\PersistentCollection\PersistentCollectionTrait;

    /**
     * @param BaseCollection $coll
     * @param DocumentManager $dm
     * @param UnitOfWork $uow
     */
    public function __construct(BaseCollection $coll, DocumentManager $dm, UnitOfWork $uow)
    {
        $this->coll = $coll;
        $this->dm = $dm;
        $this->uow = $uow;
    }

    public function __toString(): string
    {
        $this->initialize();
        if ($this->needsSchedulingForSynchronization()) {
            $this->changed();
        }
        return $this->coll->__toString();
    }

    public function matching(\Doctrine\Common\Collections\Criteria $criteria)
    {
        $this->initialize();
        if ($this->needsSchedulingForSynchronization()) {
            $this->changed();
        }
        return $this->coll->matching($criteria);
    }
}
