### Create device
POST localhost/device/create
Content-Type: application/json

{
    "Age": "15",
    "Gender": "F",
    "Gender2": "F",
    "deviceId": "2"
}

### Edit device
POST localhost/device/17/edit
Content-Type: application/json

{
    "tag1": "test32",
    "tag2": "false",
    "tag3": "0"
}

### Search device
POST localhost/device/search
Content-Type: application/json

{
    "query": "T(\"Gender\", EQ, \"F\") + T(\"Age\", LTE, 20)"
}
