### Create device
POST localhost/device/create
Content-Type: application/json

{
    "Age": 15,
    "Gender": "F",
    "Gender2": "F",
    "deviceId": "1"
}

### Edit device
POST localhost/device/1/edit
Content-Type: application/json

{
    "Age": 12,
    "Gender": "F"
}

### Search device
POST localhost/device/search
Content-Type: application/json

{
    "query": "T(\"Gender\", EQ, \"F\") + T(\"Age\", LTE, 20)"
}
